version: '3.4'
services:
  jorani:
    build: .
    ports:
      - "8080:80"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=jorani
      - MYSQL_USER=jorani
      - MYSQL_PASSWORD=jorani
      - MYSQL_TCP_PORT=3307
  mysql:
    image: mysql:8
    ports:
      - "3307:3307"
    environment:
      - MYSQL_ROOT_PASSWORD=jorani
      - MYSQL_DATABASE=jorani
      - MYSQL_USER=jorani
      - MYSQL_PASSWORD=jorani
    volumes:
      - ./sql/jorani.sql:/docker-entrypoint-initdb.d/jorani.sql
