version: '3.4'
services:
  jorani:
    build: .
    ports:
      - "8080:80" # Changed host port from 80 to 8080 to avoid conflict
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=jorani
      - MYSQL_USER=jorani
      - MYSQL_PASSWORD=jorani

  mysql:
    image: mysql:5.7 # Downgraded MySQL version to 5.7
    ports:
      - "3307:3306" # Changed host port from 3306 to 3307 to avoid conflict
    environment:
      - MYSQL_ROOT_PASSWORD=jorani
      - MYSQL_DATABASE=jorani
      - MYSQL_USER=jorani
      - MYSQL_PASSWORD=jorani
    volumes:
      - ./sql/jorani.sql:/docker-entrypoint-initdb.d/jorani.sql
